<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <!-- Self-contained настройки -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    
    <!-- Оптимизации -->
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    
    <!-- Важно: osu! обычно 32-битное -->
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HoLLy.ManagedInjector" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- DLL как встроенные ресурсы -->
    <EmbeddedResource Include="0Harmony.dll" />
    <EmbeddedResource Include="_patcher.dll" />
  </ItemGroup>
</Project>