<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PlatformTarget>x86</PlatformTarget>
    
    <UseWindowsForms>true</UseWindowsForms>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HoLLy.ManagedInjector" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="0Harmony.dll" />
    <EmbeddedResource Include="_patcher.dll" />
  </ItemGroup>
</Project>